import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CiLinkedin } from "react-icons/ci";
import React, { ReactNode } from 'react';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CyberSec",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
